name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root

    - name: Install project
      run: poetry install --no-interaction

    - name: Run doctests
      run: |
        poetry run python zbig/zfile/zcsv.py
        poetry run python zbig/ztime/cn_now.py
        poetry run python zbig/zhash/args.py
        poetry run python zbig/zcache/json_cache.py
        poetry run python zbig/zlog/logger.py
        poetry run python zbig/zconfig/settings.py

    - name: Run tests with coverage
      run: |
        poetry run pytest --cov=zbig --cov-report=xml --cov-report=term-missing

    - name: Run type checking
      run: |
        poetry run mypy zbig --ignore-missing-imports
      continue-on-error: true  # Don't fail CI if mypy has issues

    - name: Run linting
      run: |
        poetry run ruff check zbig

    - name: Run formatting check
      run: |
        poetry run ruff format --check zbig

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: matrix.python-version == '3.11'  # Only upload once
      with:
        file: ./coverage.xml
        fail_ci_if_error: false  # Don't fail CI if upload fails